---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

params:
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORGANIZATION:
  CF_SPACE:

inputs:
- name: cli
- name: edge-linux-binary-64

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    apt-get install jq

    tar -zxf edge-linux-binary-64/*.tgz

    LATEST_VERSION=$(cat cli/BUILD_VERSION)

    ./cf api "$CF_API"
    ./cf auth --client-credentials
    ./cf target -o "$CF_ORGANIZATION" -s "$CF_SPACE"
    CURRENT_VERSIONS=$(./cf env claw | grep AVAILABLE_VERSIONS | awk '{print $2}')

    if [[ $CURRENT_VERSIONS == *${LATEST_VERSION}* ]]; then
      exit
    fi

    ./cf set-env claw AVAILABLE_VERSIONS "${CURRENT_VERSIONS},${LATEST_VERSION}"
    DEPLOYMENT_GUID=$(cf curl -X POST /v3/deployments -d '{"relationships": {"app": {"data": {"guid": "'"$(./cf app claw --guid)"'"}}}}' | jq -r .guid)

    NUM_LOOPS=0
    until [ $NUM_LOOPS -eq 20 ]; do
      if [ $(./cf curl /v3/deployments/$DEPLOYMENT_GUID | jq -r .status.value) == "FINALIZED"  ]; then
         exit 0
      fi
      ((NUM_LOOPS++))
      sleep 6
    done
    exit 1
